apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redskyops/redskyops-recipes/elasticsearch
#- experiment.yam

patchesJson6902:
- target:
    group: redskyops.dev
    version: v1alpha1
    kind: Experiment
    name: elasticsearch-example-free-tier
  path: add-patches.yaml
