apiVersion: v1
kind: Service
metadata:
  name: locust
  labels:
    component: locust
spec:
  ports:
    - port: 8089
      name: dashboard
  selector:
    component: locust
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  labels:
    component: locust
spec:
  selector:
    matchLabels:
      component: locust
  template:
    metadata:
      labels:
        component: locust
    spec:
      containers:
      - image: grubykarol/locust:0.12.0-python3.7-alpine3.10
        name: locust
        command: ["/usr/local/bin/locust"]
        args: ["--locustfile=/locust-tasks/locustfile.py",
               "--host=http://voting-service"]
        volumeMounts:
        - name: locust
          mountPath: /locust-tasks/locustfile.py
          subPath: locustfile.py
        ports:
        - containerPort: 8089
          name: dashboard
      volumes:
        - name: locust
          configMap:
            name: locust
