apiVersion: redskyops.dev/v1beta1
kind: Experiment
metadata:
  labels:
    redskyops.dev/application: votingapp
    redskyops.dev/scenario: 30000-clients
  name: votingapp-30000-clients
  namespace: default
spec:
  metrics:
  - minimize: true
    name: cost-gcp
    port: 9090
    query: ({{ cpuRequests . "" }} * 17) + ({{ memoryRequests . "" | GB }} * 2)
    type: prometheus
  - minimize: true
    name: cost-gcp-cpu-requests
    optimize: false
    port: 9090
    query: '{{ cpuRequests . "" }}'
    type: prometheus
  - minimize: true
    name: cost-gcp-memory-requests
    optimize: false
    port: 9090
    query: '{{ memoryRequests . "" | GB }}'
    type: prometheus
  - minimize: true
    name: p95-latency
    port: 9090
    query: scalar(p95{job="trialRun",instance="{{ .Trial.Name }}"})
    type: prometheus
  parameters: null
  trialTemplate:
    metadata:
      labels:
        redskyops.dev/application: votingapp
        redskyops.dev/scenario: 30000-clients
    spec:
      jobTemplate:
        metadata:
          labels:
            redskyops.dev/application: votingapp
            redskyops.dev/scenario: 30000-clients
        spec:
          template:
            metadata:
              labels:
                redskyops.dev/application: votingapp
                redskyops.dev/scenario: 30000-clients
            spec:
              containers:
              - env:
                - name: HOST
                  value: http://my-nginx
                - name: NUM_USERS
                  value: "30000"
                - name: SPAWN_RATE
                  value: "1000"
                image: thestormforge/optimize-trials:v0.0.1-locust
                name: locust
                resources: {}
                volumeMounts:
                - mountPath: /mnt/locust
                  name: locustfile
                  readOnly: true
              volumes:
              - configMap:
                  name: 30000-clients-locustfile
                name: locustfile
      setupServiceAccountName: redsky-setup
      setupTasks:
      - args:
        - prometheus
        - $(MODE)
        name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    redskyops.dev/application: votingapp
  name: redsky-setup
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    redskyops.dev/application: votingapp
  name: redsky-prometheus
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  - configmaps
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    redskyops.dev/application: votingapp
  name: redsky-setup-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redsky-prometheus
subjects:
- kind: ServiceAccount
  name: redsky-setup
  namespace: default
---
apiVersion: v1
binaryData:
  locustfile.py: aW1wb3J0IG9zCgpmcm9tIHV1aWQgaW1wb3J0IHV1aWQ0CmltcG9ydCByYW5kb20KZnJvbSBsb2N1c3QgaW1wb3J0IEh0dHBVc2VyLCB0YXNrLCBiZXR3ZWVuCgoKQ0FUX0ZSQUNUSU9OID0gb3MuZ2V0ZW52KCJDQVRfRlJBQ1RJT04iLCAwLjI1KQoKCmNsYXNzIE15VXNlcihIdHRwVXNlcik6CiAgICB3YWl0X3RpbWUgPSBiZXR3ZWVuKDUsIDEwKQogICAgQHRhc2sKICAgIGRlZiB2b3RlKHNlbGYpOgogICAgICAgIHZvdGVyX2lkID0gdXVpZDQoKS5oZXgKICAgICAgICB2b3RlID0gImEiIGlmIChyYW5kb20udW5pZm9ybSgwLCAxKSA8IENBVF9GUkFDVElPTikgZWxzZSAiYiIKICAgICAgICBzZWxmLmNsaWVudC5nZXQoIi8iKQo=
kind: ConfigMap
metadata:
  labels:
    redskyops.dev/application: votingapp
  name: 30000-clients-locustfile
  namespace: default
---
